import soundgen
import numpy

with soundgen.setsamplerate(44100):
  soundgen.writewav('out.wav', numpy.concat([
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.coswave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.cos2wave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.cos3wave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.triwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.sawwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.sqrwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform(soundgen.sine(0.5, 440), soundgen.cwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.coswave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.cos2wave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.cos3wave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.triwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.sawwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.sqrwave)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.transform2(soundgen.sine(0.5, 440), soundgen.cwave)),
    soundgen.silence(0.2),
    soundgen.sine(0.5, 440),
    soundgen.silence(0.2),
    soundgen.triangle(0.5, 440),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.fouriersyn(0.5, 440, soundgen.triadditive(11))),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.triadditive(11), 1)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.triadditive(11), 2)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.fouriersyn(0.5, 440, soundgen.triadditive(80))),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.triadditive(80), 1)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.triadditive(80), 2)),
    soundgen.silence(0.2),
    soundgen.square(0.5, 440),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.fouriersyn(0.5, 440, soundgen.sqradditive(11))),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sqradditive(11), 1)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sqradditive(11), 2)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.fouriersyn(0.5, 440, soundgen.sqradditive(80))),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sqradditive(80), 1)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sqradditive(80), 2)),
    soundgen.silence(0.2),
    soundgen.saw(0.5, 440),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.fouriersyn(0.5, 440, soundgen.sawadditive(11))),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sawadditive(11), 1)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sawadditive(11), 2)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.fouriersyn(0.5, 440, soundgen.sawadditive(80))),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sawadditive(80), 1)),
    soundgen.silence(0.2),
    soundgen.adjust(soundgen.sigmasyn(0.5, 440, soundgen.sawadditive(80), 2)),
    soundgen.silence(0.2),
    soundgen.saw(2, 1760),
  ]))